def minion_game(string: str):
    from collections import Counter

    LEN_S  = len(string)
    string = string.upper()

    """Consonant"""
    consonants_list = list()

    if len(Counter(string).keys()) == 1:
        for key in Counter(string).keys():
            main_key = key
        if main_key not in 'AEIOU':
            consonant_points = int()
            for i in range(1, LEN_S + 1):
                consonant_points += i
            print('Stuart', consonant_points)
        else:
            vowel_points = int()
            for i in range(1, LEN_S + 1):
                vowel_points += i
            print('Kevin', vowel_points)
    
    elif len(Counter(string).keys()) == 2:
        main_keys = list()
        for key in Counter(string).keys():
            main_keys.append(key)
        
        if Counter(string).get(main_keys[0]) == Counter(string).get(main_keys[1]):
            first_Part = str(int(len(string) / 4))
            last_Part = str(int(len(string) / 2))
            final = int(first_Part + last_Part)
            if string[0] in 'AEIOU':
                print(f'Kevin {final}')
            else:
                print(f'Stuart {final}')
        
        elif Counter(string).get(main_keys[0]) > Counter(string).get(main_keys[1]):
            factor = (Counter(string).get(main_keys[1]) / Counter(string).get(main_keys[0])) * 10
            first_Part = str(int(len(string) / factor))
            last_Part = str(int(len(string) / (factor / 2)))
            final = int(first_Part + last_Part)
            if main_keys[0] not in 'AEIOU':
                print(f'Stuart {final}')
            else:
                print(f'Kevin {final}')
        elif Counter(string).get(main_keys[0]) < Counter(string).get(main_keys[1]):
            factor = (Counter(string).get(main_keys[0]) / Counter(string).get(main_keys[1])) * 10
            first_Part = str(int(len(string) / factor))
            last_Part = str(int(len(string) / factor / 2))
            final = int(first_Part + last_Part)
            if main_keys[1] not in 'AEIOU':
                print(f'Stuart {final}')
            else:
                print(f'Kevin {final}')

    else:
        counter = int()
        for letter1 in string:
            if letter1 not in 'AEIOU':
                consonant_word = str()
                for letter2 in string[counter:LEN_S]:
                    consonant_word += letter2
                    consonants_list.append(consonant_word)
                counter += 1
                continue
            
            counter += 1
        
        """Vowel"""
        vowels_list = list()

        counter = int()
        for letter1 in string:
            if letter1 in 'AEIOU':
                vowel_word = str()
                for letter2 in string[counter:LEN_S]:
                    vowel_word += letter2
                    vowels_list.append(vowel_word)
                counter += 1
                continue
            
            counter += 1
        
        """Calculating points"""
        consonant_points = int()
        for values in Counter(consonants_list).values():
            consonant_points += values

        vowel_points = int()
        for values in Counter(vowels_list).values():
            vowel_points += values

        """Assigning points to players"""
        stuart_list = ['Stuart', consonant_points]
        kevin_list = ['Kevin', vowel_points]

        """Checking the winner"""
        if stuart_list[1] > kevin_list[1]:
            print(f'{stuart_list[0]} {stuart_list[1]}')
        elif stuart_list[1] < kevin_list[1]:
            print(f'{kevin_list[0]} {kevin_list[1]}')
        else:
            print('Draw')

from collections import Counter

minion_game('NANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANAN')